root_path = "."

watch_target_dirs = ["../../"]
watch_exclude_dirs = [".git", "vendor", "bin"]
watch_file_ext = [".go"]

build_target_dir = "../../bin"
build_target_name = "webque-backend"
build_command = "go"
build_options = ["build", "-v"]

start_options = ["-v"]

# default true, but it's possible to make this fale, when
# running a program that doesn't persist as a process
restart_process = true
